pragma Ada_2012;
with AUnit.Assertions;        use AUnit.Assertions;
with Ada.Task_Identification; use Ada.Task_Identification;
with Ada.Text_IO;             use Ada.Text_IO;
with AUnit.Test_Fixtures;
   
package Job_Executer.Test is
   type Test is new AUnit.Test_Fixtures.Test_Fixture with null record;
   procedure test_Reached_expected_roadmarker_success (T : in out Test);  
   procedure test_Reached_expected_roadmarker_wrong_section (T : in out Test);  
   procedure test_register_new_cab_success (T : in out Test);
   procedure test_register_new_cab_failure (T : in out Test);
   procedure test_register_new_cab_timeout (T : in out Test);
   procedure test_register_new_cab_incomplete_JSON (T : in out Test);
   procedure test_register_new_cab_wrong_JSON (T : in out Test);
   procedure test_process_valid_section_reached_no_RM (T : in out Test);
   procedure test_process_valid_section_reached_RM (T : in out Test);
   procedure test_process_valid_section_reached_RM_Wait (T : in out Test);
   procedure test_process_valid_section_reached_RM_Pickup (T : in out Test);
   procedure test_process_valid_section_reached_RM_Pickup_BE_failed (T : in out Test);
   procedure test_process_valid_section_reached_RM_Dropoff (T : in out Test);
   procedure test_process_valid_section_reached_RM_Dropoff_BE_failed (T : in out Test);
   procedure test_process_section_update_section_success (T : in out Test);
   procedure test_process_section_update_section_failure (T : in out Test);
   procedure test_process_section_reached_RM (T : in out Test);
   procedure test_process_section_reached_non_existent_RM (T : in out Test);
   procedure test_process_section_no_RM (T : in out Test);
   procedure test_process_section_system_error (T : in out Test);
   procedure test_update_route_success_not_in_section (T : in out Test);
   procedure test_update_route_success_in_section (T : in out Test);
   procedure test_update_route_failure (T : in out Test);
   procedure test_update_route_incomplete_JSON (T : in out Test);
   procedure test_update_route_wrong_JSON (T : in out Test);
   procedure test_update_route_timeout (T : in out Test);
   procedure test_update_route_same_version(T : in out Test);
   procedure test_determine_done_signal_LEFT(T : in out Test);
   procedure test_determine_done_signal_RIGHT(T : in out Test);
   procedure test_determine_done_signal_UNKNOWN(T : in out Test);
   procedure test_determine_done_signal_WAIT(T : in out Test);
   procedure test_determine_done_signal_STOP(T : in out Test);
   procedure test_determine_done_signal_PICKUP_instant_success(T : in out Test);
   procedure test_determine_done_signal_double_PICKUP_instant_success (T : in out Test);
   procedure test_determine_done_signal_PICKUP_failure(T : in out Test);
   procedure test_determine_done_signal_PICKUP_incomplete_JSON(T : in out Test);
   procedure test_determine_done_signal_PICKUP_wrong_JSON(T : in out Test);
   procedure test_determine_done_signal_PICKUP_timeout(T : in out Test);
   procedure test_determine_done_signal_PICKUP_late_failure(T : in out Test);
   procedure test_determine_done_signal_PICKUP_not_completed(T : in out Test);
   procedure test_determine_done_signal_DROPOFF_instant_success(T : in out Test);
   procedure test_determine_done_signal_double_DROPOFF_instant_success (T : in out Test);
   procedure test_determine_done_signal_DROPOFF_failure(T : in out Test);
   procedure test_determine_done_signal_DROPOFF_incomplete_JSON(T : in out Test);
   procedure test_determine_done_signal_DROPOFF_wrong_JSON(T : in out Test);
   procedure test_determine_done_signal_DROPOFF_timeout(T : in out Test);
   procedure test_determine_done_signal_DROPOFF_late_failure(T : in out Test);
   procedure test_determine_done_signal_DROPOFF_not_completed(T : in out Test);

end Job_Executer.Test;
